use_frameworks!

target 'TBFontAdjust_Example' do
  pod 'TBFontAdjust', :podspec => '../TBFontAdjust.podspec'

  target 'TBFontAdjust_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
